version: "3.2"
services:

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
    networks:
      - mynet

  backend:    
    restart: always
    build:
      context: ./
    volumes:
      - .:/src
    depends_on:
      - mongodb
    environment:
      PORT: 4000
      MONGO_URL: mongodb://mongodb:27017/mydb
      ACCESS_TOKEN_SECRET: tokenjwtlalalal
    ports:
        - 4000:4000
    networks:
      - mynet

networks:
  mynet:
    driver: bridge 